# Generated by Django 5.1 on 2024-08-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(default='Kenya', max_length=50),
            preserve_default=False,
        ),
    ]
